### ISSUE TITLE
Issues awareness

### ISSUE THREAD

**Issue by TimKam** [jacamo-lang/jacamo-web#21]
Develop issue awareness UI

**Comment by cleberjamaral** [comment]
We can split it into two reporting functions:
1) When trying to push his version, notice the current developer that there are errors/warnings (Maybe he is ignoring those ones when he was editing some agent or it just happened after another developer push some change in a related agent)
2) Provide a way to make other developers aware of issues that become open after the last push. Maybe we could have a window to show these open issues.

**Comment by cleberjamaral** [comment]
Format: 
issues =
[
{ level: 'warning', message: 'lorem ipsum' },
{ level: 'hint', message: 'lorem ipsum' },
{ level: 'error', message: 'lorem ipsum' }
]

**Comment by cleberjamaral** [comment]
Basic /lock and /unlock end-points are available. Closes #26

**Comment by cleberjamaral** [comment]
The websocket endpoint could be used for this purpose. The current format is in plain text saying "developedName locked resourceName". Indeed, a list of messages is maybe not suitable at this time because the messages are pushed directly to all opened ws connections (no buffering).

**Comment by cleberjamaral** [comment]
Since we now have an interface that shows the user open issues before committing, I am closing this issue.
